"""D2. Contract-stub pre-pass — scaffold placeholder files for the task DAG.

After the PRD is parsed and the task list is materialized, the engine calls
scaffold_dag_stubs() ONCE before the task loop. For every file declared in any
task's files[] that does not already exist in the workspace, it creates a stub
file carrying the task's title + acceptance criteria as a module docstring —
so later tasks can read the contract and code against it (cross-task import
resolution vanishes behind a single call).

A stub is a placeholder. The targeting rail (D3) treats "file == stub
content" as NOT-yet-implemented.
"""

import logging
import os

log = logging.getLogger(__name__)

# Marker comment placed at the end of every stub so the targeting rail can
# detect untouched stubs deterministically.
STUB_MARKER = "# ACE_STUB: generated by scaffold_dag_stubs — replace with real implementation."


def is_stub(content: str) -> bool:
    """Return True if file content is an untouched D2 stub (the targeting
    rail uses this to flag 'declared but not yet implemented' files)."""
    return STUB_MARKER in content


def _stub_text(task, path: str) -> str:
    """Build the stub file content: module docstring carrying the task's
    title + acceptance criteria so downstream tasks can read the contract."""
    lines = [
        '"""Stub for ' + path + ".",
        "",
        "Task: " + task.id + " — " + task.title,
        "",
    ]
    ac = getattr(task, "acceptance_criteria", None) or []
    if ac:
        lines.append("Acceptance criteria:")
        for c in ac:
            lines.append("  - " + c)
        lines.append("")
    lines.append("This file is a placeholder. Code against its contract; replace")
    lines.append("with a real implementation during the task loop.")
    lines.append('"""')
    lines.append("")
    lines.append(STUB_MARKER)
    lines.append("")
    return "\n".join(lines)


def scaffold_dag_stubs(workspace_path: str, tasks: list) -> list[str]:
    """Create a stub file for every declared file[] entry not already present.

    Idempotent: a second call creates nothing (existing files are left
    untouched, even if they are themselves stubs — the task loop fills them).

    Args:
        workspace_path: absolute path to the project root.
        tasks: the parsed task list (each task has .id, .title, .files,
               .acceptance_criteria).

    Returns:
        list of created stub paths (relative to workspace_path).
    """
    if not workspace_path or not tasks:
        return []

    created: list[str] = []
    # Deduplicate: the same file may appear in multiple tasks' files[].
    seen: set[str] = set()

    for task in tasks:
        for fpath in (getattr(task, "files", None) or []):
            if fpath in seen:
                continue
            seen.add(fpath)
            full = os.path.join(workspace_path, fpath)
            if os.path.exists(full):
                continue
            # Ensure parent dir exists.
            parent = os.path.dirname(full)
            if parent and not os.path.isdir(parent):
                try:
                    os.makedirs(parent, exist_ok=True)
                except OSError as exc:
                    log.warning("stub: could not create parent dir %s: %s",
                                parent, exc)
                    continue
            try:
                with open(full, "w", encoding="utf-8") as fh:
                    fh.write(_stub_text(task, fpath))
                created.append(fpath)
                log.debug("stub created: %s (task %s)", fpath, task.id)
            except OSError as exc:
                log.warning("stub: could not write %s: %s", fpath, exc)

    return created
